# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunbo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '蘑菇街_轮播图2',
            },
        ),
    ]
