# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-04 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_lunbo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('marketprice', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': '蘑菇街_产品信息',
            },
        ),
    ]
