# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Register')),
            ],
            options={
                'db_table': '蘑菇街_购物车',
            },
        ),
    ]
